# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e47199e4c2b94dd358427fdd30051a55f5f54a8ccb0d2c5be69a73e7a6dd3260b0126c9d81262f28ad1ddc7bfa03bc93eb5ff494e3a06f87d7178904a76b5a9

test:
  secret_key_base: 8a3fbdaacd117b1dfcf828c5d6c01aea6cf76163f17720f28134f1e7e760415514ca11f6eae0ca748e45025f5eb8359401e662fb7e49d1e13543a8767b5c0492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
